[build]
  publish = "public"
#  command = "npm run build && npm run ipfs-deploy"
  command = "npm run build"

[context.production.environment]
  HUGO_VERSION = "0.67.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "https://lhwcrt.netlify.com/*"
  to = "https://blog.lhwcrt.top/:splat"
  status = 301
  force = true 
