[build]
  publish = "public"
  command = "yarn run build && yarn run ipfs-deploy"
#  command = "yarn run build"

[context.production.environment]
  HUGO_VERSION = "0.79.1"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "https://lhwcrt.netlify.com/*"
  to = "https://blog.coelacanthus.moe/:splat"
  status = 301
  force = true
