[build]
  publish = "public"
  command = "yarn run build && npm run ipfs-deploy"
#  command = "yarn run build"

[context.production.environment]
  HUGO_VERSION = "0.73.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "https://lhwcrt.netlify.com/*"
  to = "https://blog.lhwcrt.top/:splat"
  status = 301
  force = true
