#[[main]]
#    url = "/"
#    name = "首页"
#    weight = 1
#    pre = "internal"
#    post = "home"
#    identifier = "home"
[[main]]
    url = "/archives/"
    name = "归档"
    weight = 2
    pre = "internal"
    post = "archive"
    identifier = "archives"
#[[main]]
#    url = "/posts/"
#    name = "文章"
#    weight = 3
#    pre = "internal"
#    post = "archive"
#    identifier = "posts"
[[main]]
    url = "/tags/"
    name = "标签"
    weight = 5
    pre = "internal"
    post = "tags"
    identifier = "tags"
[[main]]
    url = "/friends/"
    name = "友链"
    weight = 6
    pre = "internal"
    post = "archive"
    identifier = "friends"
[[main]]
    url = "/about/"
    name = "关于"
    weight = 7
    pre = "internal"
    post = "user-circle"
    identifier = "about"
[[main]]
    weight = 8
    identifier = "theme-switcher"
[[main]]
    weight = 9
    identifier = "lang-switcher"
#[[main]]
#    weight = 10
#    identifier = "search"
#    post = "search"
