#[[main]]
#    url = "/zh-tw/"
#    name = "首頁"
#    weight = 1
#    pre = "internal"
#    post = "home"
#    identifier = "home"
[[main]]
    url = "/zh-tw/archives/"
    name = "歸檔"
    weight = 2
    pre = "internal"
    post = "archive"
    identifier = "archives"
#[[main]]
#    url = "/zh-tw/posts/"
#    name = "文章"
#    weight = 3
#    pre = "internal"
#    post = "archive"
#    identifier = "posts"
[[main]]
    url = "/zh-tw/tags/"
    name = "標籤"
    weight = 5
    pre = "internal"
    post = "tags"
    identifier = "tags"
[[main]]
    url = "/zh-tw/friends/"
    name = "友鏈"
    weight = 6
    pre = "internal"
    post = "archive"
    identifier = "friends"
[[main]]
    url = "/zh-tw/about/"
    name = "關於"
    weight = 7
    pre = "internal"
    post = "user-circle"
    identifier = "about"
[[main]]
    weight = 8
    identifier = "theme-switcher"
[[main]]
    weight = 9
    identifier = "lang-switcher"
#[[main]]
#    weight = 10
#    identifier = "search"
#    post = "search"
